server:
  port: 8888

spring:
  application:
    name: rd-platform
  config:
    import: optional:file:./config/application-local.yaml
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/rd_platform?serverTimezone=Asia/Shanghai&useSSL=false
    username: root

mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
